version: '3.0'
services:
  app:
    build: 
      context: .
      dockerfile: ./docker/app/go/Dockerfile
    command: tail -f /dev/null
    volumes:
      - storage_app:/var/lib/mysql
      - ./webapp:/home/ishocon/webapp
    ports:
      - "443:443"
      - "3306:3306"
      - "8080:8080"

  bench:
    image: showwin/ishocon2_bench:latest
    command: tail -f /dev/null
    volumes:
      - storage_bench:/var/lib/mysql
    links:
      - app
    environment: 
      - TARGET=app

volumes:
  storage_bench:
  storage_app:
